name: Fetch new data

on: 
  workflow_dispatch:
  schedule: 
    - cron: '0 * * * *' # Berjalan setiap jam

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ke branch main
        uses: actions/checkout@v2 # checkout the repository content
      
      - name: Lokalisasi bahasa dan tanggal
        run: |
          timedatectl set-timezone Asia/Jakarta

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2' # install the python version needed

      - name: Install library python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Menjalankan script scrapping
        run: python main.py

      - name: Commit perubahan
        run: |
          git config --local user.email "hlfeyexist@proton.me"
          git config --local user.name "Yobel D. ( GitHub Actions )"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "cronjob: update news information" --allow-empty)

      - name: Push ke branch main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
